### ISSUE TITLE
Typo in "Creating an actor"

### ISSUE THREAD

**Issue by clasnake** [jasongoodwin/learning-akka#1]
Hi, I've been reading the book on Safari Online. It's fantastic!
In section "Creating an actor" of Chapter 2, seems "variable lengle list" in the first paragraph of "Props" should be "variable length list".
![image](https://cloud.githubusercontent.com/assets/1590497/12574943/4874a734-c443-11e5-8644-44b9c524d073.png)

Thanks.

**Comment by jasongoodwin** [comment]
Hey - thanks so much for raising this! I'll let the publisher know that some errata was found. My worst fear is that there is more!
Not even urban dictionary has a definition of the word lengle so that must be a typo. :)
Closing issue as it's not actionable in the code here.

**Comment by clasnake** [comment]
Thanks! I've been reading this great book and I'm wondering if there's a channel for errata reporting. If any more errata is found, shall I still raise issues here or email some address?

**Comment by jasongoodwin** [comment]
Hey, let me ask the publisher. They will publish eratta for other readers
so I very much appreciate it. Putting it here until I get back to you would
be fine. Thanks so much again! I hope the read is okay otherwise.
